const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/advanceController');
const { protect } = require('../middleware/auth');
router.get('/balance', protect, ctrl.getBalance);
router.get('/', protect, ctrl.getAll);
router.get('/:id', protect, ctrl.getOne);
router.post('/', protect, ctrl.create);
router.put('/:id', protect, ctrl.update);
router.delete('/:id', protect, ctrl.remove);
module.exports = router;
